<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGinyynv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGinyynv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGinyynv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGinyynv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGinyynv\appProdProjectContainer([
    'container.build_hash' => 'Ginyynv',
    'container.build_id' => '47d81e0b',
    'container.build_time' => 1610276344,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGinyynv');
